name: Portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decode SSH key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | base64 -d > awskey.pem
          chmod 600 awskey.pem

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: awskey.pem
          script: |
            cd /home/ubuntu/portfolio || git clone git@github.com:Mukezh/Actualportfolio.git portfolio && cd portfolio
            git reset --hard HEAD
            git pull origin master
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/

